### ISSUE TITLE
[discussion] split databases from files

### ISSUE THREAD

**Issue by yoshuawuyts** [joehand/dat-node-deprecated#6]
I tried downloading two files in the same directory the other day, but `dat` wouldn't let me because it already had a database in the dir. How would you feel about splitting off the databases from the actual files and store them in `~/.level` using https://github.com/yoshuawuyts/named-level-store ?

I feel this would make it a bit more predictable to manage leveldb instances, not only in `dat` but also in lower level tools like `hyperdrive`, `normcore`, `hyperreduce` and the like. For `dat-desktop` I also had to spend a bit of time tracking down the database to reset it which like isn't great. Keen to hear thoughts!

**Comment by okdistribute** [comment]
I think this should be discussed on a call instead of typing to minimize back and forth. @mafintosh @maxogden and @jhand probably have more to say regarding .dat file in the local folder vs. in the home folder. We have talked about it a bunch in person as well as online and decided on the .dat folder next to the files to mimic git's behavior, but happy to discuss more.

**Comment by yoshuawuyts** [comment]
yeah so talked about it on IRC and doesn't seem like a great idea for right now; thanks for the patience :sparkles:

**Comment by yoshuawuyts** [comment]
Oh PS if we ever do decide to go down the route of using multiple hyperdrives, I wrote https://github.com/yoshuawuyts/multidrive yesterday which might be useful - not yet for SLEEP files but yeah hah
